// Generated by CoffeeScript 1.6.3
var NumberRange,
  __slice = [].slice;

NumberRange = (function() {
  function NumberRange() {
    var max, min, num, range, _i, _len;
    range = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    min = null;
    max = null;
    for (_i = 0, _len = range.length; _i < _len; _i++) {
      num = range[_i];
      if ((min == null) || num < min) {
        min = num;
      }
      if ((max == null) || num > max) {
        max = num;
      }
    }
    if ((max == null) || (min == null)) {
      this.isValid = false;
    }
    this.min = min;
    this.max = max;
  }

  NumberRange.prototype.isValid = function() {
    return this.isValid;
  };

  return NumberRange;

})();

module.exports = {
  NumberRange: NumberRange
};
