// Generated by CoffeeScript 1.6.3
var config, err, validate;

validate = require('./validation');

config = require('uniformer')({
  defaults: {
    debug: false,
    secret: "critic_app_secret_294802483",
    key: "critic_session",
    title: "Critic",
    id: "github_api_id",
    port: 3000,
    whitelist: ["js", "cs", "cpp", "md", "html", "json", "c", "py", "lisp", "hs"]
  }
});

if ((err = validate(config, "port", "debug", "secret", "key", "title", "id")) !== false) {
  console.log(err);
  process.exit(-1);
}

module.exports = config;
