// Generated by CoffeeScript 1.6.3
var helpers;

helpers = require('reqall')();

module.exports = {
  org: function(gh, req, res) {
    return helpers["user-orgs"](gh, function(err, r) {
      var i, org, repos, _i, _len, _results;
      if (err != null) {
        return helpers.log(res, err);
      }
      if (r.meta.status !== '200 OK') {
        return helpers.log(res, new helpers.GithubApiError(r.meta.status));
      }
      repos = [];
      _results = [];
      for (i = _i = 0, _len = r.length; _i < _len; i = ++_i) {
        org = r[i];
        _results.push(helpers["org-repos"](gh, function(err, r) {
          if (err != null) {
            return helpers.log(res, err);
          }
          if (r.meta.status !== '200 OK') {
            return helpers.log(res, new helpers.GithubApiError(r.meta.status));
          }
          repos.push({
            org: org.login,
            repos: r
          });
          if (i + 1 > r.length) {
            return res.send(repos);
          }
        }, org.login));
      }
      return _results;
    });
  },
  user: function(gh, req, res) {
    return res.send("this flow isn't done yet!");
  }
};
