// Generated by CoffeeScript 1.6.3
var api, config, github;

api = require('github');

config = require('./configuration');

github = new api({
  version: "3.0.0",
  debug: config.debug,
  protocol: "https",
  host: "api.github.com",
  timeout: 5000
});

if (config["access_token"] != null) {
  github.authenticate({
    type: "oauth",
    token: config["access_token"]
  });
}

module.exports = github;
