// Generated by CoffeeScript 1.6.3
var __slice = [].slice;

module.exports = function() {
  var msg, msgs, _i, _len, _results;
  msgs = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
  _results = [];
  for (_i = 0, _len = msgs.length; _i < _len; _i++) {
    msg = msgs[_i];
    _results.push(console.log(typeof msg + " says " + msg));
  }
  return _results;
};
