// Generated by CoffeeScript 1.6.3
var __slice = [].slice;

module.exports = function() {
  var config, err, i, miss, missing, prop, props, _i, _j, _len, _len1;
  config = arguments[0], props = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
  if (config === null) {
    return "HALT: no config specified!!";
  } else {
    missing = [];
    for (_i = 0, _len = props.length; _i < _len; _i++) {
      prop = props[_i];
      if (config[prop] == null) {
        missing.push(prop);
      }
    }
    err = "HALT: missing ";
    for (i = _j = 0, _len1 = missing.length; _j < _len1; i = ++_j) {
      miss = missing[i];
      if (i + 1 < missing.length) {
        err += miss + ", ";
      } else {
        err += missing.length > 1 ? "and " : "" + miss;
      }
    }
    if (missing.length === 0) {
      err = false;
    }
    return err;
  }
};
