// Generated by CoffeeScript 1.6.3
var app, config, express, flow, k, log, route, swig;

express = require('express');

swig = require('swig');

config = require('./helpers/configuration');

log = require('./helpers/log');

app = express();

app.use(express["static"](__dirname + '/public'));

app.use(express.cookieParser());

app.use(express.session({
  secret: config.secret,
  key: config.key
}));

app.engine('swig', swig.renderFile);

app.set('view engine', 'swig');

app.set('views', __dirname + '/views');

flow = require("./flow");

for (k in flow) {
  route = flow[k];
  if ((route.method != null) && (route.path != null) && (route.handler != null)) {
    app[route.method](route.path, route.handler);
  } else {
    log("InvalidFlow: ", route);
  }
}

app.listen(config.port);

console.log("critic up on " + config.port);
