// Generated by CoffeeScript 1.6.3
(function() {
  var config, critic, file, fs, swig, uniformer, _i, _len, _ref;

  uniformer = require('uniformer');

  swig = require('swig');

  critic = require('./critic');

  fs = require('fs');

  config = uniformer({
    file: 'config.json',
    defaults: {
      url: "localhost",
      port: "80",
      callback: "#authorized",
      root: "public/"
    }
  });

  if ((config.port == null) || (config.callback == null) || (config.token == null) || (config.root == null)) {
    console.log("oops, invalid configuration! at least specify token and secret please!");
    process.exit(-1);
  }

  _ref = fs.readdirSync('swig');
  for (_i = 0, _len = _ref.length; _i < _len; _i++) {
    file = _ref[_i];
    fs.writeFileSync('public/' + file.split('.swig')[0] + ".html", swig.renderFile(file, fs.readFileSync(file.split('.swig')[0] + ".json") || {}));
  }

  critic(config.port, config.root, config.token, "http://" + config.url + "/" + config.callback);

}).call(this);
