// Generated by CoffeeScript 1.6.3
(function() {
  var config, critic, uniformer;

  uniformer = require('uniformer');

  critic = require('./critic');

  config = uniformer({
    file: 'config.json',
    defaults: {
      url: "localhost",
      port: "80",
      callback: "#authorized",
      root: "public/"
    }
  });

  if ((config.port == null) || (config.callback == null) || (config.token == null) || (config.root == null)) {
    console.log("oops, invalid configuration! at least specify token and secret please!");
    process.exit(-1);
  }

  critic(config.port, config.root, config.token, "http://" + config.url + "/" + config.callback);

}).call(this);
