// Generated by CoffeeScript 1.6.3
(function() {
  var apiMatcher, authMatcher, http, request, send;

  http = require('http');

  send = require('send');

  request = require('request');

  apiMatcher = new RegExp("^/github-api/");

  authMatcher = new RegExp("^/github-auth$");

  module.exports = function(port, root, client_id, redirect_uri) {
    var app;
    app = http.createServer(function(req, res) {
      if (authMatcher.test(req.url)) {
        return req.pipe(request("https://github.com/login/oauth/authorize?client_id=" + client_id + "&redirect_uri=" + redirect_uri + "&scope=user:email,repo")).pipe(res);
      } else if (apiMatcher.test(req.url)) {
        return req.pipe(request("https://api.github.com/" + req.url.split('/github-api/')[1])).pipe(res);
      } else {
        return send(req, req.url).root(root).pipe(res);
      }
    }).listen(port);
    return console.log("critic instance up on " + port + ", serving " + root);
  };

}).call(this);
